### ISSUE TITLE
Why does the base AMI use a different owner ID?

### ISSUE THREAD

**Issue by jsf9k** [cisagov/assessor-workbench-packer#20]
# 🐛 Summary #

This repo has the same issue described in cisagov/pca-gophish-composition-packer#78.

**Comment by dav3r** [comment]
See issue #2 for the background on this.  It seems that we closed that issue after https://github.com/cisagov/skeleton-packer/pull/83 was merged, but never actually reverted the owner ID back to `136693071363` for this repo.

@jsf9k, @mcdonnnj I'm fine with changing the owner ID back to `136693071363` as part of PR #19 if you are.

**Comment by jsf9k** [comment]
> @jsf9k, @mcdonnnj I'm fine with changing the owner ID back to `136693071363` as part of PR #19 if you are.

I'd prefer a separate PR.

**Comment by dav3r** [comment]
OK, I'm fine with a separate PR for this.
